### ISSUE TITLE
EPIC v2 support

### ISSUE THREAD

**Issue by andrewjkwok** [timpeters82/DMRcate-devel#5]
Hi,

I'm looking to some differential methylation analysis on EPIC v2 data. As I understand it, after limma differential analysis, I can collapse the probes into various regions with DMRcate. However, I can't seem to find any support currently for the EPIC v2 arrays - just wanted ot check whether there is any plan for this to be supported?

Many thanks in advance.

**Comment by timpeters82** [comment]
Hi Andrew,

Yes, support for EPICv2 will be coming shortly. There are a few extra probe filtering steps that will be needed but I'll rewrite `cpg.annotate()` appropriately for this in the interim. Many thanks for your interest.

Cheers,
Tim

**Comment by andrewjkwok** [comment]
Thanks for the quick reply Tim, looking forward to the EPICv2 support.

Checking the code of the `cpg.annotate` function, it seems that a key step is the `getAnnotation` call on the genomicratioset, but does that depend on minfi support for EPICv2? I can't seem to find the relevant minfi support at the moment actually...

**Comment by timpeters82** [comment]
Yes, we plan to provide our own support for EPICv2 in the coming weeks. Stay tuned.

Best,
Tim

**Comment by andrewjkwok** [comment]
Thanks Tim, looking forward to it.

**Comment by timpeters82** [comment]
Hi Andrew,

DMRcate can now call DMRs from EPICv2 in the current devel version: https://www.bioconductor.org/packages/devel/bioc/html/DMRcate.html. You can find the vignette for EPICv2 assays here: https://www.bioconductor.org/packages/devel/bioc/vignettes/DMRcate/inst/doc/EPICv2.pdf

This version will become 3.0 in the next Bioconductor release, available May 1st.

If you're interested, you can also check out our latest paper in BMC Genomics (https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-024-10027-5), where we take a deep dive into many aspects of EPICv2, including reproducibility and multiple probes mapping to the same CpG site.

Cheers,
Tim
