### ISSUE TITLE
DMR identification for mice methylation array with time-course analysis 

### ISSUE THREAD

**Issue by dtzhu337** [timpeters82/DMRcate-devel#6]
Hi there,

We have a longitudinal study where plasma sample from mice at multiple ages were subjected to Illumina Methylation array. In this case, we would like to identify differential methylated CpGs (DMCs) that globally changed over the time-course, hence, we used limma time-course analysis with the intra-block correlation based block on mouse ID. We then would like to identify DMRs using dmrcate function. However, I found that the time course analysis was not a case included in the function. I understand the idea of the DMRs identification is to identify genomic regions where DMCs enriched in. Any suggestion on how I can modify the functions within the package to achieve this, especially how to indicate mice methylation array data and time-course analysis (limma)? Thank you in advance.

Best

**Comment by timpeters82** [comment]
Hello,

You can pass the `block` and `correlation` arguments from `lmFit()` as part of the ellipsis (`...`) in `cpg.annotate()`, and it will incorporate these appropriately into DMR calling. For the time course analysis part, you can order your timepoint factor using `factor(timepoint, ordered=TRUE, levels=c("t0", "t1", "t2` etc. and it will give you linear, quadratic and polynomial coefficients, for which you can choose 1 to pass to `cpg.annotate()`.

As an aside, DMCs are certainly enriched in DMRs, but the kernel itself is agnostic to the threshold, which is applied afterwards.

Best,
Tim
