### ISSUE TITLE
EPICv2 - rmSNPandCH - XY Removal

### ISSUE THREAD

**Issue by ReWeda** [timpeters82/DMRcate-devel#7]
Hello there,

Context:
DMRcate v.3.0.3
DMRcatedata v.2.22.0
EPICv2manifest v0.99.7 (from Peters et al. (2024))

When I run the `rmSNPandCH` function on uncollapsed M values (with the full probe names still present) while attempting to remove XY probes (`rmXY = TRUE`), I encounter the following error:

`Error in exists(EPICv2manifest) : invalid first argument`

No error returned setting `rmXY = FALSE`

Right now, I'm bypassing the error manually removing XY probes from the M values matrix.

**Comment by timpeters82** [comment]
Well spotted, thanks Davide. "EPICv2manifest" wasn't in quotes.

Git is now updated and should propagate to release and devel.

Cheers,
Tim
